#!/usr/bin/env bash
# ============================================================
# NeuraLabs Command Center — Installer
# Run: chmod +x install.sh && sudo ./install.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
  echo -e "${CYAN}║   NeuraLabs Command Center — Installer   ║${NC}"
  echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
  echo ""
}

info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

ask() {
  local prompt="$1" default="${2:-}" var_name="$3" secret="${4:-false}"
  if [ -n "$default" ]; then prompt="$prompt [${default}]"; fi
  echo -en "${CYAN}> ${NC}${prompt}: "
  if [ "$secret" = "true" ]; then read -rs val; echo ""; else read -r val; fi
  val="${val:-$default}"
  eval "$var_name=\"\$val\""
}

ask_required() {
  local prompt="$1" var_name="$2" secret="${3:-false}"
  while true; do
    ask "$prompt" "" "$var_name" "$secret"
    eval "local v=\"\$$var_name\""
    [ -n "$v" ] && break
    error "This field is required."
  done
}

# ── PRE-FLIGHT CHECKS ──────────────────────────────────────
banner

if [ "$EUID" -ne 0 ]; then
  error "Please run as root: sudo ./install.sh"
  exit 1
fi

info "Checking system requirements..."

if ! grep -qi "ubuntu" /etc/os-release 2>/dev/null; then
  warn "This installer is designed for Ubuntu. Proceeding anyway..."
fi

TOTAL_RAM=$(free -m | awk '/^Mem:/ {print $2}')
if [ "$TOTAL_RAM" -lt 1800 ]; then
  error "Minimum 2GB RAM required. Found: ${TOTAL_RAM}MB"
  exit 1
fi

FREE_DISK=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
if [ "$FREE_DISK" -lt 5 ]; then
  error "Minimum 5GB free disk required. Found: ${FREE_DISK}GB"
  exit 1
fi

ok "System checks passed (RAM: ${TOTAL_RAM}MB, Disk: ${FREE_DISK}GB free)"

# ── CONFIGURATION (minimal — rest via setup wizard) ───────
echo ""
echo -e "${CYAN}═══ AUTHENTICATION ═══${NC}"
ask_required "Dashboard login password" CC_PASSWORD true
CC_SESSION_SECRET=$(openssl rand -hex 32)
ok "Session secret auto-generated"

echo ""
echo -e "${CYAN}═══ INSTALLATION ═══${NC}"
ask "Install directory" "/opt/commandcenter" INSTALL_DIR

# All other config is done via the setup wizard in the browser
COMPANY_NAME=""
ASSISTANT_NAME=""
TAGLINE=""
PRIMARY_COLOR_HUE=264
PRIMARY_COLOR_SAT=65
PRIMARY_COLOR_LIT=49
ANTHROPIC_API_KEY=""
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
HEYGEN_API_KEY=""
STRIPE_SECRET_KEY=""
COMPOSIO_API_KEY=""
DASHBOARD_URL="http://localhost:3000"

# ── INSTALL SYSTEM DEPENDENCIES ───────────────────────────
echo ""
info "Installing system dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq

# Node.js 18+
if ! command -v node &>/dev/null || [ "$(node -v | tr -d 'v' | cut -d. -f1)" -lt 18 ]; then
  info "Installing Node.js 18..."
  curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  apt-get install -y -qq nodejs
fi
ok "Node.js $(node -v)"

# Python 3
if ! command -v python3 &>/dev/null; then
  apt-get install -y -qq python3 python3-venv python3-pip
fi
ok "Python $(python3 --version)"

# Redis
if ! command -v redis-server &>/dev/null; then
  apt-get install -y -qq redis-server
  systemctl enable redis-server
  systemctl start redis-server
fi
ok "Redis installed"

# Claude Code (optional — timeout after 60s)
info "Installing Claude Code..."
if timeout 60 npm install -g @anthropic-ai/claude-code 2>&1 | tail -3; then
  ok "Claude Code installed"
else
  warn "Claude Code install timed out or failed — install later with: npm install -g @anthropic-ai/claude-code"
fi

# Inference.sh (optional — timeout after 60s)
info "Installing Inference.sh..."
if timeout 60 npm install -g inference.sh 2>&1 | tail -3; then
  ok "Inference.sh installed"
else
  warn "Inference.sh install timed out or failed — install later with: npm install -g inference.sh"
fi

pip3 install -q python-dotenv 2>/dev/null || true

# ── COPY FILES ────────────────────────────────────────────
info "Installing to ${INSTALL_DIR}..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

mkdir -p "$INSTALL_DIR"

# Copy Command Center components
for component in command-center config; do
  if [ -d "$SCRIPT_DIR/$component" ]; then
    cp -r "$SCRIPT_DIR/$component" "$INSTALL_DIR/"
  fi
done

cp "$SCRIPT_DIR/.env.example" "$INSTALL_DIR/"
ok "Files copied to $INSTALL_DIR"

# ── WRITE .ENV ────────────────────────────────────────────
info "Writing .env configuration..."

cat > "$INSTALL_DIR/.env" <<EOF
# Generated by installer on $(date -u +"%Y-%m-%d %H:%M UTC")
# Branding & integrations are configured via the setup wizard
COMPANY_NAME=${COMPANY_NAME}
ASSISTANT_NAME=${ASSISTANT_NAME}
TAGLINE=${TAGLINE}
PRIMARY_COLOR_HUE=${PRIMARY_COLOR_HUE}
PRIMARY_COLOR_SAT=${PRIMARY_COLOR_SAT}
PRIMARY_COLOR_LIT=${PRIMARY_COLOR_LIT}
CC_PASSWORD=${CC_PASSWORD}
CC_SESSION_SECRET=${CC_SESSION_SECRET}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
HEYGEN_API_KEY=${HEYGEN_API_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
COMPOSIO_API_KEY=${COMPOSIO_API_KEY}
BRAND_ASSET_URL=
INSTALL_DIR=${INSTALL_DIR}
DASHBOARD_URL=${DASHBOARD_URL}
EOF

chmod 600 "$INSTALL_DIR/.env"
ok ".env written (permissions: 600)"

# ── GENERATE COMPONENT CONFIGS ───────────────────────────
info "Generating configs..."
chmod +x "$INSTALL_DIR/config/generate-configs.sh"
bash "$INSTALL_DIR/config/generate-configs.sh"

# ── INSTALL NODE.JS DEPENDENCIES ─────────────────────────
info "Installing Command Center dependencies (this may take a few minutes)..."
cd "$INSTALL_DIR/command-center" && npm install --production 2>&1 | tail -5
ok "Command Center npm packages installed"

# Playwright browsers (needed for slide designer and browser tools)
info "Installing Playwright browsers..."
if npx playwright install chromium 2>&1 | tail -3; then
  npx playwright install-deps chromium 2>&1 | tail -3
  ok "Playwright Chromium installed"
else
  warn "Playwright install failed — slide designer won't work. Install later with: npx playwright install chromium"
fi

# ── INSTALL SYSTEMD SERVICES ────────────────────────────
info "Installing systemd services..."

for tpl in "$INSTALL_DIR/config/systemd/"*.tpl; do
  svc_name=$(basename "$tpl" .service.tpl)
  sed "s|{{INSTALL_DIR}}|${INSTALL_DIR}|g" "$tpl" > "/etc/systemd/system/${svc_name}.service"
  ok "  ${svc_name}.service installed"
done

systemctl daemon-reload

systemctl enable command-center --quiet 2>/dev/null
systemctl start command-center 2>/dev/null || warn "Failed to start command-center — check: journalctl -u command-center"
ok "Command Center service started"

# ── INSTALL CRON JOBS ───────────────────────────────────
if [ -f "$INSTALL_DIR/config/cron/crontab.tpl" ]; then
  info "Installing cron jobs..."
  chmod +x "$INSTALL_DIR/command-center/daily-research-trigger.sh" 2>/dev/null || true
  CRON_CONTENT=$(sed "s|{{INSTALL_DIR}}|${INSTALL_DIR}|g" "$INSTALL_DIR/config/cron/crontab.tpl")
  (crontab -l 2>/dev/null || true; echo "$CRON_CONTENT") | crontab -
  ok "Cron jobs installed"
fi

# ── OPEN FIREWALL ────────────────────────────────────────
info "Opening firewall port 3004..."
iptables -I INPUT -p tcp --dport 3004 -j ACCEPT 2>/dev/null || true
ufw allow 3004 2>/dev/null || true
# Persist iptables rules if possible
if command -v netfilter-persistent &>/dev/null; then
  netfilter-persistent save 2>/dev/null || true
elif command -v iptables-save &>/dev/null; then
  iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
fi
ok "Firewall port 3004 opened"

# ── VERIFICATION ────────────────────────────────────────
echo ""
info "Verifying installation..."
sleep 3

if systemctl is-active --quiet command-center 2>/dev/null; then
  ok "Command Center is running"
else
  warn "Command Center is not running — check: journalctl -u command-center -n 20"
fi

# ── SUMMARY ─────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║   Installation Complete!                  ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

SERVER_IP=$(hostname -I | awk '{print $1}')

echo -e "  ${GREEN}▸ VOLGENDE STAP:${NC}"
echo -e "  Open ${CYAN}http://${SERVER_IP}:3004${NC} in je browser"
echo -e "  Log in met je wachtwoord en volg de setup wizard."
echo ""
echo -e "  De wizard helpt je configureren:"
echo "    - Branding (naam, kleuren, tagline)"
echo "    - Anthropic API key (AI functies)"
echo "    - Telegram notificaties"
echo "    - Integraties (HeyGen, Stripe, Composio)"
echo ""
echo -e "  ${YELLOW}Trading Bots:${NC}"
echo "    Trading bots zijn een aparte addon."
echo "    Installeer ze later via: github.com/neuralabscloud/neuralabs-trading-bots"
echo ""
echo -e "  ${YELLOW}Manage services:${NC}"
echo "    systemctl status command-center"
echo "    systemctl restart command-center"
echo "    journalctl -u command-center -f"
echo ""
echo -e "${GREEN}Done! Open http://${SERVER_IP}:3004 om te beginnen.${NC}"
