import type { Project } from "../types";
import { generateId } from "../store";

export type Template = {
  id: string;
  name: string;
  description: string;
  icon: string;
  aspectRatio: "16:9" | "9:16" | "1:1";
  create: () => Project;
};

export const templates: Template[] = [
  {
    id: "trading-recap",
    name: "Trading Recap",
    description: "Short recap of your trading day with key stats",
    icon: "chart",
    aspectRatio: "9:16",
    create: () => ({
      name: "Trading Recap",
      fps: 30,
      aspectRatio: "9:16",
      audioSrc: null,
      audioVolume: 0.8,
      scenes: [
        {
          id: generateId(),
          type: "title",
          durationInFrames: 90,
          transition: "fade",
          backgroundColor: "#06080d",
          title: "DAILY RECAP",
          subtitle: "March 24, 2026",
          titleColor: "#00e5ff",
          subtitleColor: "#64748b",
          titleSize: 72,
          animation: "scale",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 120,
          transition: "slide",
          backgroundColor: "#0a0e17",
          heading: "Key Trades",
          body: "BTC Long +2.4%\nETH Short +1.8%\nSOL Long +3.1%",
          headingColor: "#00e5ff",
          bodyColor: "#e2e8f0",
          textAlign: "left",
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 120,
          transition: "slide",
          backgroundColor: "#0a0e17",
          heading: "Performance",
          body: "Win Rate: 78%\nTotal PnL: +$1,240\nBest Trade: SOL +3.1%",
          headingColor: "#00ffaa",
          bodyColor: "#e2e8f0",
          textAlign: "left",
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "outro",
          durationInFrames: 90,
          transition: "fade",
          backgroundColor: "#06080d",
          title: "Follow for Daily Recaps",
          cta: "SUBSCRIBE",
          titleColor: "#e2e8f0",
          ctaColor: "#a855f7",
          animation: "scale",
        },
      ],
    }),
  },
  {
    id: "education",
    name: "Education / Tutorial",
    description: "Explain a concept step by step with clear visuals",
    icon: "book",
    aspectRatio: "9:16",
    create: () => ({
      name: "Education Video",
      fps: 30,
      aspectRatio: "9:16",
      audioSrc: null,
      audioVolume: 0.8,
      scenes: [
        {
          id: generateId(),
          type: "title",
          durationInFrames: 90,
          transition: "fade",
          backgroundColor: "#0a0e17",
          title: "Did You Know?",
          subtitle: "Funding Rate Explained",
          titleColor: "#a855f7",
          subtitleColor: "#e2e8f0",
          titleSize: 64,
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 150,
          transition: "slide",
          backgroundColor: "#0d1220",
          heading: "What is Funding Rate?",
          body: "Funding rate is a periodic payment between long and short traders in perpetual futures markets.",
          headingColor: "#00e5ff",
          bodyColor: "#e2e8f0",
          textAlign: "left",
          animation: "typewriter",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 150,
          transition: "slide",
          backgroundColor: "#0d1220",
          heading: "How Does It Work?",
          body: "Positive rate: Longs pay shorts\nNegative rate: Shorts pay longs\n\nThis keeps futures price aligned with spot.",
          headingColor: "#00e5ff",
          bodyColor: "#e2e8f0",
          textAlign: "left",
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 120,
          transition: "slide",
          backgroundColor: "#0d1220",
          heading: "Pro Tip",
          body: "You can farm funding by collecting payments while hedging your position.",
          headingColor: "#ffaa22",
          bodyColor: "#e2e8f0",
          textAlign: "center",
          animation: "fade",
        },
        {
          id: generateId(),
          type: "outro",
          durationInFrames: 90,
          transition: "fade",
          backgroundColor: "#06080d",
          title: "Learn More",
          cta: "FOLLOW FOR TIPS",
          titleColor: "#e2e8f0",
          ctaColor: "#00e5ff",
          animation: "scale",
        },
      ],
    }),
  },
  {
    id: "social-clip",
    name: "Social Clip",
    description: "Quick attention-grabbing clip for TikTok/Reels",
    icon: "zap",
    aspectRatio: "9:16",
    create: () => ({
      name: "Social Clip",
      fps: 30,
      aspectRatio: "9:16",
      audioSrc: null,
      audioVolume: 0.8,
      scenes: [
        {
          id: generateId(),
          type: "title",
          durationInFrames: 60,
          transition: "none",
          backgroundColor: "#06080d",
          title: "STOP SCROLLING",
          subtitle: "",
          titleColor: "#ff4466",
          subtitleColor: "#64748b",
          titleSize: 80,
          animation: "scale",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 120,
          transition: "slide",
          backgroundColor: "#0a0e17",
          heading: "",
          body: "This one trick will change how you trade forever...",
          headingColor: "#e2e8f0",
          bodyColor: "#e2e8f0",
          textAlign: "center",
          animation: "typewriter",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 120,
          transition: "slide",
          backgroundColor: "#0d1220",
          heading: "The Secret",
          body: "Always check the funding rate before entering a position.",
          headingColor: "#00ffaa",
          bodyColor: "#e2e8f0",
          textAlign: "center",
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "outro",
          durationInFrames: 75,
          transition: "fade",
          backgroundColor: "#06080d",
          title: "Save This",
          cta: "SHARE WITH A FRIEND",
          titleColor: "#e2e8f0",
          ctaColor: "#a855f7",
          animation: "fade",
        },
      ],
    }),
  },
  {
    id: "announcement",
    name: "Announcement",
    description: "Big announcement or news drop",
    icon: "megaphone",
    aspectRatio: "9:16",
    create: () => ({
      name: "Announcement",
      fps: 30,
      aspectRatio: "9:16",
      audioSrc: null,
      audioVolume: 0.8,
      scenes: [
        {
          id: generateId(),
          type: "title",
          durationInFrames: 75,
          transition: "fade",
          backgroundColor: "#0a0e17",
          title: "BIG NEWS",
          subtitle: "You won't want to miss this",
          titleColor: "#ffaa22",
          subtitleColor: "#e2e8f0",
          titleSize: 80,
          animation: "scale",
        },
        {
          id: generateId(),
          type: "text",
          durationInFrames: 150,
          transition: "slide",
          backgroundColor: "#0d1220",
          heading: "Announcement",
          body: "Your announcement text goes here. Make it impactful and clear.",
          headingColor: "#00e5ff",
          bodyColor: "#e2e8f0",
          textAlign: "center",
          animation: "slide-up",
        },
        {
          id: generateId(),
          type: "outro",
          durationInFrames: 90,
          transition: "fade",
          backgroundColor: "#06080d",
          title: "Stay Tuned",
          cta: "TURN ON NOTIFICATIONS",
          titleColor: "#e2e8f0",
          ctaColor: "#ffaa22",
          animation: "fade",
        },
      ],
    }),
  },
];
